### ISSUE TITLE
Command prepare not found on container startup

### ISSUE THREAD

**Issue by BernhardFuchs** [jolocom/jolo-did-method#41]
Just pulled the new image and the startup fails with:
```
yarn run v1.13.0
$ yarn prepare && node js/index.js
error Command "prepare" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

_Originally posted by @BernhardFuchs in https://github.com/jolocom/jolo-did-method/issues/36#issuecomment-759512856_

**Comment by mnzaki** [comment]
@BernhardFuchs apologies there was small issue!
A new docker image was just published (and tested....) and seems to be working this time :sweat_smile:

**Comment by BernhardFuchs** [comment]
Np and thx for the quick fix, the driver works now.
